# COCO 2017 dataset http://cocodataset.org
# Train command: python train.py --data coco.yaml
# Default dataset location is next to YOLOv5:
#   /parent_folder
#     /coco
#     /yolov5


# download command/URL (optional)

train: <TRAINING YOLO IMAGE DIRECTORY>
val: <VALIDATION YOLO IMAGE DIRECTORY>
#test: /media/data1/nips-experiment/experiments/street_test/images  # 20288 of 40670 images, submit to https://competitions.codalab.org/competitions/20794

# number of classes
nc: 2
names: ['normal', 'swoon']
# class names
# Print classes
# with open('data/coco.yaml') as f:
#   d = yaml.safe_load(f)  # dict
#   for i, x in enumerate(d['names']):
#     print(i, x)
